version: '3.0'
services:
  db:
    image: mysql:8.0
    container_name: lacuna-pdb
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "lacunadb"
      MYSQL_USER: lacunauser
      MYSQL_PASSWORD: lacunauserpwd
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  app:
    depends_on:
      - db
    image: imvictr/lacuna-depl:1.5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
volumes:
  dbdata: