global using Xunit;
global using FluentAssertions;
global using Lacuna.Domain.Interfaces;
global using Lacuna.Domain.Users;
global using Lacuna.Infrastructure.Context;
global using Lacuna.Infrastructure.Repository;
global using Lacuna.InfrastructureTests.Fixtures;
global using MockQueryable.Moq;
global using Moq;